stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
      - src/data/split_data.py
      - data/raw_data/raw.csv
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - src/data/normalize_data.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv
      - models/scaler.pkl

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - src/models/grid_search.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    outs:
      - models/best_model_params.pkl
      - models/grid_search_results.json

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - models/best_model_params.pkl
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    outs:
      - models/trained_model.pkl
      - models/training_info.json

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - models/trained_model.pkl
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
    outs:
      - data/predictions.csv
      - metrics/scores.json